version: '3'

services:
  landing:
    build:
      context: landing
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certificates:/etc/nginx/ssl
      - ./crypto/spinmerightround/index.html:/usr/share/nginx/html/spinmerightround.html:ro
    environment:
      DOMAIN: demo.unbcybersec.com
      USE_CERTBOT: true
      CERTBOT_EMAIL: letsencrypt@unbcybersec.com

  web_dictionary:
    build:
      context: challenges/web/dictionary
      dockerfile: Dockerfile
    ports:
      - "50023:80"

  web_cats:
    build:
      context: challenges/web/cats
      dockerfile: Dockerfile
    ports:
      - "50011:80"
  
  web_adminsonly:
    build:
      context: challenges/web/adminsonly
      dockerfile: Dockerfile
    ports:
      - "50040:3000"

  web_calculator:
    build:
      context: challenges/web/calculator
      dockerfile: Dockerfile
    ports:
      - "50036:5000"