services:
  landing:
    build:
      context: landing
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certificates:/etc/nginx/ssl
    environment:
      DOMAIN: <your-domain>
      USE_CERTBOT: true
      CERTBOT_EMAIL: <your-email>

  mariadb:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: changme
      MYSQL_DATABASE: scoreboard
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - "./api/db:/var/lib/mysql"

  api:
    build:
      context: api
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:9000:9000"
    environment:
      DB_PASS: <mariadb pass>
      DOMAIN: <domain for your instance>
      FLASK_KEY: <secret for flask>
      JWT_KEY: <secret for signing jwt>
      FLAG: <current challenge flag>
      DISABLED: 0 # set to 1 if you wish to disable submissions

  chall:
    build:
      context: challenges/<chall folder>
      dockerfile: Dockerfile
    ports:
      - "1337:1337" #fix as needed
